import type { Metadata } from "next";
import localFont from "next/font/local";
import "./nextjs/globals.css";

const geistSans = localFont({
  src: "./nextjs/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./nextjs/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
          <meta name="description" content=""/>
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
          <link rel="stylesheet" href="/css/bootstrap.min.css"/>
          <link rel="stylesheet" href="/css/slick.css"/>
          <link rel="stylesheet" href="/css/slick-theme.css"/>
          <link rel="stylesheet" href="/css/feature.css"/>
          <link rel="stylesheet" href="/css/style.css"/>

          {/*<link*/}
          {/*    rel="stylesheet"*/}
          {/*    href={"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"}*/}
          {/*    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"*/}
          {/*    crossOrigin="anonymous"*/}
          {/*/>*/}
          {/*<link*/}
          {/*    rel="stylesheet"*/}
          {/*    type="text/css"*/}
          {/*    charSet="UTF-8"*/}
          {/*    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"*/}
          {/*/>*/}
          {/*<link*/}
          {/*    rel="stylesheet"*/}
          {/*    type="text/css"*/}
          {/*    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"*/}
          {/*/>*/}
          <title>Portfolio | Nicholas</title>
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {children}
      </body>
      </html>
  );
}
